# Repository label definitions (to be synced by workflow)
# Name and color must be stable; description is optional.

- name: "module: animate"
  color: "0e8a16"
  description: "Changes in modules/animate"
- name: "module: arduino_serial"
  color: "0e8a16"
  description: "Changes in modules/arduino_serial"
- name: "module: calibration"
  color: "0e8a16"
  description: "Changes in modules/calibration"
- name: "module: camera"
  color: "0e8a16"
  description: "Changes in modules/camera"
- name: "module: config_center"
  color: "0e8a16"
  description: "Changes in modules/config_center"
- name: "module: diagnostics"
  color: "0e8a16"
  description: "Changes in modules/diagnostics"
- name: "module: gateway"
  color: "0e8a16"
  description: "Changes in modules/gateway"
- name: "module: hardware"
  color: "0e8a16"
  description: "Changes in modules/hardware"
- name: "module: interactions"
  color: "0e8a16"
  description: "Changes in modules/interactions"
- name: "module: logwrapper"
  color: "0e8a16"
  description: "Changes in modules/logwrapper"
- name: "module: mutagen"
  color: "0e8a16"
  description: "Changes in modules/mutagen"
- name: "module: neopixel"
  color: "0e8a16"
  description: "Changes in modules/neopixel"
- name: "module: notifier"
  color: "0e8a16"
  description: "Changes in modules/notifier"
- name: "module: ollama"
  color: "0e8a16"
  description: "Changes in modules/ollama"
- name: "module: ota"
  color: "0e8a16"
  description: "Changes in modules/ota"
- name: "module: piservo"
  color: "0e8a16"
  description: "Changes in modules/piservo"
- name: "module: scheduler"
  color: "0e8a16"
  description: "Changes in modules/scheduler"
- name: "module: speak"
  color: "0e8a16"
  description: "Changes in modules/speak"
- name: "module: speech"
  color: "0e8a16"
  description: "Changes in modules/speech"
- name: "module: state_manager"
  color: "0e8a16"
  description: "Changes in modules/state_manager"
- name: "module: telemetry"
  color: "0e8a16"
  description: "Changes in modules/telemetry"
- name: "module: vision_bridge"
  color: "0e8a16"
  description: "Changes in modules/vision_bridge"
- name: "module: wiki_rag"
  color: "0e8a16"
  description: "Changes in modules/wiki_rag"
