server:
  host: 0.0.0.0
  port: 8091

network:
  ssid: "SentryBOT"
  password: "SentryBOT"

base_url: "http://sentrybot-2.local:8080"
paths:
  health: "/healthz"
  send: "/send"
  request: "/request"

timeouts:
  connect_s: 0.4
  io_s: 1.2
