# Auto-generated by 30_fix_testclient_cleanup_ps51.ps1.
# Keeps third-party Starlette/FastAPI TestClient deprecation noise out of project tests.
from __future__ import annotations

import warnings

try:
    from starlette.exceptions import StarletteDeprecationWarning as _StarletteDeprecationWarning
except Exception:  # pragma: no cover - compatibility fallback
    _StarletteDeprecationWarning = Warning

warnings.filterwarnings(
    "ignore",
    message=r".*Using `httpx` with `starlette\.testclient` is deprecated.*",
    category=_StarletteDeprecationWarning,
)
warnings.filterwarnings(
    "ignore",
    message=r".*Using `httpx` with `starlette\.testclient` is deprecated.*",
    category=Warning,
)
warnings.filterwarnings(
    "ignore",
    message=r".*starlette\.testclient.*deprecated.*",
    category=Warning,
)
