services:
  sentrybot-gateway:
    environment:
      GATEWAY_CONFIG: /app/modules/gateway/config/config.docker.rpi.yml
      ARDUINO_PORT: ${ARDUINO_PORT:-/dev/ttyACM0}

    # Raspberry Pi / Linux cihaz gecisleri.
    # Ihtiyaca gore azaltilip arttirilabilir.
    devices:
      - ${ARDUINO_PORT:-/dev/ttyACM0}:${ARDUINO_PORT:-/dev/ttyACM0}
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiomem:/dev/gpiomem
      - /dev/video0:/dev/video0

    volumes:
      - ./modules/gateway/config/config.docker.rpi.yml:/app/modules/gateway/config/config.docker.rpi.yml:ro

    privileged: true
