server:
  host: 0.0.0.0
  port: 8097

ota:
  ota:
  watch_dir: arduino/firmware/xMain/build
  artifact_glob: "*.hex"
  board:
    mcu: atmega328p
    programmer: arduino
    baud: 115200
    port: COM3  # Windows örnek
  avrdude:
    bin: avrdude
    config: null
    extra_flags: []
  version_db: modules/ota/config/versions.json
  scan_on_start: true
  security:
    enable_allowlist: false
    enable_signature: false
    allowed_hashes: []
    secret_key: ""  # Set if enabling signature verification

esp_ota:
  base_url: "http://sentrybot-2.local"
  port: 80
  watch_dir: arduino/firmware/esp_bridge/build
  artifact_glob: "*.bin"
  auth: ""  # Optional Bearer token for ESP OTA
  version_db: modules/ota/config/versions_esp.json
  security:
    enable_allowlist: false
    enable_signature: false
    allowed_hashes: []
    secret_key: ""
