server:
  host: 0.0.0.0
  port: 8097

ota:
  watch_dir: arduino/firmware/xMain/build
  artifact_glob: "*.hex"
  board:
    mcu: atmega328p
    programmer: arduino
    baud: 115200
    port: COM3  # Windows örnek
  avrdude:
    bin: avrdude
    config: null
    extra_flags: []
  version_db: modules/ota/config/versions.json
  scan_on_start: true
