server:
  host: 0.0.0.0
  port: 8092

hardware:
  device: "/dev/spidev0.0"
  num_leds: 30
  speed_khz: 800
  order: "GRB"  # GRB|RGB|BRG

defaults:
  rainbow:
    wait: 0.02
    cycles: 3
  theater_chase:
    r: 255
    g: 0
    b: 0
    wait: 0.05
    cycles: 10
